config/routes.rb
Rails.application.routes.draw do

  resources :payments

  resource :cart, only: [:show] do
    put "add/:product_id", to: "carts#add", as: :add_to
    put "remove/:product_id", to: "carts#remove", as: :remove_from
  end

  root  :to       => "welcome#index"
  get   "about"   => "welcome#about"
  get   "contact" => "welcome#contact"

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  get     "login"     => "sessions#new"
  post    "login"     => "sessions#create"
  delete  "logout"    => "sessions#destroy"
  get     "register"  => "users#new"
  get "account" => "users#show"

  resources :products,    only: [:show, :index]

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  validates :name, presence: true

  has_many :products
end

app/models/category.rb
class Category < ActiveRecord::Base
  acts_as_nested_set

  has_many :products

  validates :name, presence: true

end

app/models/payment.rb
class Payment < ActiveRecord::Base

  belongs_to :user
  belongs_to :status, class_name: "PaymentStatus", foreign_key: "payment_status_id"
  has_many :items, class_name: "PaymentItem", foreign_key: "payment_id"

end

app/models/payment_item.rb
class PaymentItem < ActiveRecord::Base
  belongs_to :payment
  belongs_to :product
end

app/models/payment_status.rb
class PaymentStatus < ActiveRecord::Base
  SUCCESS = 1
  FAIL = 2
  ERROR = 3
  PROCESSING = 4
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :brand

  validates :name, presence: true, length: { minimum: 6 }
  validates :price, numericality: true

  def cart_action(current_user_id)
    $redis.hget("cart#{current_user_id}", id) ? "Remove from" : "Add to"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token

  before_save { self.email = email.downcase }

  validates :name,  presence: true,
                    length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }

  has_many :payments


  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, remember_token)
  end

  def authenticated?(remember_token)
    remember_digest == remember_token
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def cart_count
    $redis.hlen "cart#{id}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include CartsHelper

  private

  def logged_in_user
    unless logged_in?
      flash[:error] = "Please log in before continue."
      redirect_to login_path
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :logged_in_user

  def show
    @cart_hash = cart_hash
    @cart_products = Product.find(@cart_hash.keys)
    @cart_total = cart_total(@cart_hash, @cart_products)
  end

  def add
    $redis.hincrby current_user_cart, params[:product_id], params[:qty]
    render json: { count: current_user.cart_count }, status: 200
  end

  def remove
    $redis.hdel current_user_cart, params[:product_id]
    render json: { count: current_user.cart_count, total: cart_total(cart_hash) }, status: 200
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def create
    carts = cart_hash
    products ||= Product.find(carts.keys)
    qty_errors = insufficient_items(carts, products).inject([]) do |errors, product|
      errors << "#{product.name} has only #{product.qty} #{'unit'.pluralize(product.qty)} left\n"
    end

    if qty_errors
      flash[:error] = qty_errors
      return redirect_to cart_path
    end

    amount = cart_total(carts, products)

    payment = Payment.create(user: current_user, amount: amount,
      payment_status_id: PaymentStatus::PROCESSING)
    record_items(payment, products, carts)

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card  => params[:stripeToken]
    )
    Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => (amount * 100).round,
      :description => "Rails Stripe customer",
      :currency    => "gbp"
    )

    flash[:success] = "Successfully completed payment with amount #{amount}"
    payment.update_attributes(payment_status_id: PaymentStatus::SUCCESS)
    clear_cart
    redirect_to cart_path
  rescue Exception => e
    payment.update_attributes(payment_status_id: PaymentStatus::FAIL)
    flash[:error] = "Payment fails because #{e.message}"
    redirect_to cart_path
  end

  private

  def record_items(payment, products, carts)
    products.each do |product|
      price, qty = product.price, carts[product.id]
      PaymentItem.create(payment: payment, product: product,
        qty: qty, price: product.price, total: price * qty)
    end
  end

  def insufficient_items(carts, products)
    products.select { |product| product.qty < carts[product.id] }
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @new_products = Product.last(3)
    @sellers = Product.take(3)
  end

  def show
    @product = Product.find_by(id: params[:id])
    @cart_action = @product.cart_action current_user.try :id
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_path if logged_in?
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      remember user
      redirect_to root_path
    else
      flash.now[:error] = "Invalid email/password combination"
      render "new"
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user && @user.save
      log_in @user
      remember @user
      redirect_to root_path
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email,
      :password, :password_confirmation,
      :addr_one, :addr_two,
      :city, :country, :postcode)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @new_products = Product.last(3)
    @sellers = Product.take(3)
    @brands = Brand.take(7)
    @feature_products = @brands.map { |brand| brand.products.sample }
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def cart_hash
    Hash[$redis.hgetall(current_user_cart).map{ |k, v| [k.to_i, v.to_i] }]
  end

  def cart_total(cart_hash, products = nil)
    products ||= Product.find(cart_hash.keys)
    products.reduce(0) { |sum, product| sum + product.price * cart_hash[product.id] }.to_f
  end

  def current_user_cart
    "cart#{current_user.id}"
  end

  def clear_cart
    $redis.del current_user_cart
  end
end

app/helpers/payments_controller_helper.rb
module PaymentsControllerHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in user
    session[:user_id] = user.id
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget user
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by(id: user_id)
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    current_user
  end

  def log_out
    forget current_user
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/show.html.haml
- content_for :head do
  = stylesheet_link_tag "carts"

- provide(:bg_title, "shopping cart")

/ start main
.main_bg
  .wrap
    .main
      %table#cart
        %thead
          %tr
            %th.first Photo
            %th.second Qty
            %th.third Product
            %th.fourth Line Total
            %th.fifth Remove
        %tbody
          / shopping cart contents
          - @cart_products.each do |product|
            %tr.productitm{:id => product.id}
              %td= product.id
              %td
                %input.qtyinput{:max => "99", :min => "1", :type => "number", :value => @cart_hash[product.id]}/
              %td= product.name
              %td= "£#{product.price}"
              %td
                %a.button{"data-product_id" => product.id, "data-removeurl" => remove_from_cart_path(product), :href => "", :confirm => "Are you sure you want to do that?"}
                  %i.fa.fa-times

          %tr.totalprice
            %td.light Total:
            %td{:colspan => "2"}
            %td{:colspan => "2"}
              %span.simpleCart_grandTotal= @cart_total
          / checkout btn
          %tr.checkoutrow
            %td.checkout{:colspan => "5"}
              = form_tag payments_path, style: 'margin-left: 0px;margin-right: 0px;' do
                %script.stripe-button{"data-amount" => (@cart_total*100).round, "data-description" => "Checkout", "data-key" => Rails.configuration.stripe[:publishable_key], "data-email" => current_user.email, "data-allow-remember-me" => "false", "data-currency" => "GBP", src: "https://checkout.stripe.com/checkout.js"}

app/views/payments_controller/create.html.haml
%h1 PaymentsController#create
%p Find me in app/views/payments_controller/create.html.haml

app/views/products/index.html.haml
- provide(:bg_title, "our products")

.main_bg
  .wrap
    .main
      .top_main
        %h2 new arrivals on ifurniture
        %a{:href => "#"} show all
        .clear
      / start grids_of_3
      .grids_of_3
        - @new_products.each do |product|
          .grid1_of_3
            %a{:href => product_path(product)}
              %img{:alt => "", :src => asset_path("pic1.jpg")}/
              %h3= product.name
              %span.price= "£#{product.price}"
        .clear
      .top_main
        %h2 best sellers of the month
        %a{:href => "#"} show all
        .clear
      / start grids_of_3
      .grids_of_3
        - @new_products.each do |product|
          .grid1_of_3
            %a{:href => product_path(product)}
              %img{:alt => "", :src => asset_path("pic3.jpg")}/
              %h3= product.name
              %span.price= "£#{product.price}"
        .clear
      .clear

app/views/products/show.html.haml
- content_for :head do
  = javascript_include_tag  "jquery.fancybox.pack"

- provide(:bg_title, "ifurniture")

:javascript
  jQuery(document).ready(function(){
      // This button will increment the value
      $('.qtyplus').click(function(e){
          // Stop acting like a button
          e.preventDefault();
          // Get the field name
          fieldName = $(this).attr('field');
          // Get its current value
          var currentVal = parseInt($('input[name='+fieldName+']').val());
          // If is not undefined
          if (!isNaN(currentVal)) {
              // Increment
              $('input[name='+fieldName+']').val(currentVal + 1);
          } else {
              // Otherwise put a 0 there
              $('input[name='+fieldName+']').val(0);
          }
      });
      // This button will decrement the value till 0
      $(".qtyminus").click(function(e) {
          // Stop acting like a button
          e.preventDefault();
          // Get the field name
          fieldName = $(this).attr('field');
          // Get its current value
          var currentVal = parseInt($('input[name='+fieldName+']').val());
          // If it isn't undefined or its greater than 0
          if (!isNaN(currentVal) && currentVal > 0) {
              // Decrement one
              $('input[name='+fieldName+']').val(currentVal - 1);
          } else {
              // Otherwise put a 0 there
              $('input[name='+fieldName+']').val(0);
          }
      });
  });


.main_bg
  .wrap
    .main
      / start content
      .single
        / start span1_of_1
        .left_content
          .span1_of_1
            / start product_slider
            .product-view
              .product-essential
                .product-img-box
                  .more-views
                    .more-views-container
                      %ul
                        %li
                          %a.cs-fancybox-thumbs{:alt => "", "data-fancybox-group" => "thumb", :href => "", :title => ""}
                            %img{:alt => "", :src => "", :src_main => "", :title => ""}/
                        %li
                          %a.cs-fancybox-thumbs{:alt => "", "data-fancybox-group" => "thumb", :href => "", :title => ""}
                            %img{:alt => "", :src => "", :src_main => "", :title => ""}/
                        %li
                          %a.cs-fancybox-thumbs{:alt => "", "data-fancybox-group" => "thumb", :href => "", :title => ""}
                            %img{:alt => "", :src => "", :src_main => "", :title => ""}/
                        %li
                          %a.cs-fancybox-thumbs{:alt => "", "data-fancybox-group" => "thumb", :href => "", :title => ""}
                            %img{:alt => "", :src => "", :src_main => "", :title => ""}/
                        %li
                          %a.cs-fancybox-thumbs{:alt => "", "data-fancybox-group" => "thumb", :href => "", :title => ""}
                            %img{:alt => "", :src => "", :src_main => "", :title => ""}/
                  .product-image
                    %a.cs-fancybox-thumbs.cloud-zoom{:alt => "Women Shorts", "data-fancybox-group" => "thumb", :href => asset_path("0001-2.jpg"), :rel => "adjustX:30,adjustY:0,position:'right',tint:'#202020',tintOpacity:0.5,smoothMove:2,showTitle:true,titleOpacity:0.5", :title => "Women Shorts"}
                      %img{:alt => "Women Shorts", :src => asset_path("0001-2.jpg"), :title => "Women Shorts"}/

          / start span1_of_1
          .span1_of_1_des
            .desc1
              %h3= @product.name
              %h5= "£#{@product.price}"
              .available
                .btn_form
                  %form
                    #qty_selector
                      %input.qtyminus{:field => "quantity", :type => "button", :value => "-"}/
                      %input.qty{:name => "quantity", :type => "number", :value => "1", :min => "1", :max => @product.qty}/
                      %input.qtyplus{:field => "quantity", :type => "button", :value => "+"}/

                    = link_to "", class: "button", data: {target: @cart_action, addUrl: add_to_cart_path(@product), removeUrl: remove_from_cart_path(@product)} do
                      %i.fi-shopping-cart
                      %span= @cart_action
                      Cart
                %p= @product.description_markup
              .share-desc
                .share
                  %h4 Share Product :
                  %ul.share_nav
                    %li
                      %a{:href => "#"}
                        %img{:src => asset_path("facebook.png"), :title => "facebook"}/
                    %li
                      %a{:href => "#"}
                        %img{:src => asset_path("twitter.png"), :title => "Twiiter"}/
                    %li
                      %a{:href => "#"}
                        %img{:src => asset_path("rss.png"), :title => "Rss"}/
                    %li
                      %a{:href => "#"}
                        %img{:src => asset_path("gpluse.png"), :title => "Google+"}/
                .clear
          .clear
          / start left content_bottom
          .left_content_btm
            %p.para= @product.description
            / start tabs
            %section.tabs
              %input#tab-1.tab-selector-1{:checked => "checked", :name => "radio-set", :type => "radio"}/
              %label.tab-label-1{:for => "tab-1"} overview
              %input#tab-2.tab-selector-2{:name => "radio-set", :type => "radio"}/
              %label.tab-label-2{:for => "tab-2"} consumer
              %input#tab-3.tab-selector-3{:name => "radio-set", :type => "radio"}/
              %label.tab-label-3{:for => "tab-3"} semiconductor
              .clear-shadow
              .content
                .content-1
                  %p.para.top
                    %span= @product.description
                  .clear
                .content-2
                  %p.para
                    %span WELCOME
                    Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections
                  %ul.qua_nav
                    %li Multimedia Systems
                    %li Digital media adapters
                    %li Set top boxes for HDTV and IPTV Player applications on various Operating Systems and Hardware Platforms
                .content-3
                  %p.para.top
                    %span LOREM IPSUM
                    There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined
                  %ul
                    %li Research
                    %li Design and Development
                    %li Porting and Optimization
                    %li System integration
                    %li Verification, Validation and Testing
                    %li Maintenance and Support
                  .clear
            / end tabs
          / end left content_bottom
        .clear
      / end content

app/views/users/new.html.haml
- provide(:bg_title, "login or create an account")

.main_bg
  .wrap
    .main
      .login_left
        %h3 login customers
        %p if you have any account with us, please log in.
        / start registration
        .registration
          /
            [if IE]
            < link rel='stylesheet' type='text/css' href='ie.css'/>
            [endif]
          /
            [if lt IE 7]>
            < link rel='stylesheet' type='text/css' href='ie6.css'/>
            <! [endif]
          :javascript
            (function() {

                  // Create input element for testing
                  var inputs = document.createElement('input');

                  // Create the supports object
                  var supports = {};

                  supports.autofocus   = 'autofocus' in inputs;
                  supports.required    = 'required' in inputs;
                  supports.placeholder = 'placeholder' in inputs;

                  // Fallback for autofocus attribute
                  if(!supports.autofocus) {

                  }

                  // Fallback for required attribute
                  if(!supports.required) {

                  }

                  // Fallback for placeholder attribute
                  if(!supports.placeholder) {

                  }

                  // Change text inside send button on submit
                  var send = document.getElementById('register-submit');
                  if(send) {
                    send.onclick = function () {
                      this.innerHTML = '...Sending';
                    }
                  }

                })();
          .registration_left
            .registration_form
              / Form
              = form_for(:session, url: login_path, html: {id: "registration_form"}) do |f|
                %div
                  %label
                    = f.text_field :email, tabindex: "3", placeholder: "Email", required: "", type: "email"
                %div
                  %label
                    = f.password_field :password, tabindex: "4", placeholder: "Password", required: "", type: "password"
                %div
                  = f.submit "Login", id: "register-submit"
                .forget
                  %a{:href => "#"} forgot your password
        / end registration
      .login_left
        %h3 register new customers
        %p By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping address, view and track your orders in your accoung and more.
        .registration_left
          .registration_form
            / Form
            = form_for(@user, html: {id: "registration_form"}) do |f|
              = render "shared/error_message", object: f.object
              %div
                %label
                  = f.text_field :name, tabindex: "1", placeholder: "Name", required: "", type: "text"
              %div
                %label
                  = f.text_field :email, tabindex: "2", placeholder: "Email", required: "", type: "email"
              %div
                %label
                  = f.password_field :password, tabindex: "3", placeholder: "Password", required: "", type: "password"
              %div
                %label
                  = f.password_field :password_confirmation, tabindex: "4", placeholder: "Retype password", required: "", type: "password"

              %h3 Optional
              %div
                %label
                  = f.password_field :addr_one, tabindex: "5", placeholder: "Address one", type: "text"
              %div
                %label
                  = f.password_field :addr_two, tabindex: "6", placeholder: "Address two", type: "text"
              %div
                %label
                  = f.password_field :city, tabindex: "7", placeholder: "City", type: "text"
              %div
                %label
                  = f.password_field :country, tabindex: "8", placeholder: "Country", type: "text"
              %div
                %label
                  = f.password_field :postcode, tabindex: "9", placeholder: "Postcode", type: "text"
              %div
                = f.submit "create an account", id: "register-submit"
            / /Form
      .clear

app/views/users/show.html.haml
- provide(:bg_title, "Account")

- content_for :head do
  = stylesheet_link_tag "users"

.main_bg
  .wrap
    .main
      .project
        .cont.span_2_of_3
          .blog
            .blogsidebar.span_1_of_blog
              %ul.blog-list
                %li
                  Posted on
                  %br>/
                  January 20, 2014
                %li
                  Tags
                  %br/
                  = succeed "\u{a0}" do
                    %a{:href => "#"} Website
                  %a{:href => "#"} Design
                %li
                  Comments
                  %br/
                  %a{:href => "#"} 8
            .cont.span_2_of_blog
              %p.para Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
              %p.para Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
            .clear
          .about-left
            %h3
              %a{:href => "#"} Payments
          .blog
            - current_user.payments.each do |payment|
              .blogsidebar.span_1_of_blog
                %ul.blog-list
                  %li
                    ID
                    %br>/
                    = payment.id
                  %li
                    Posted on
                    %br>/
                    %a{:href => "#"}= "#{time_ago_in_words(payment.created_at)} ago"
                  %li
                    Status
                    %br/
                    %a{:href => "#"}= payment.status.name.upcase
                  %li
                    Amount
                    %br/
                    %a{:href => "#"}= "£#{payment.amount}"
              .cont.span_2_of_blog
                %table.table.table-striped.table-hover
                  %thead
                    %tr
                      %th Product
                      %th Qty
                      %th Price
                      %th Line Total
                  %tbody
                    - payment.items.each do |item|
                      %tr
                        %td= item.product.name
                        %td= item.qty
                        %td= item.price
                        %td= item.total
              .clear
              %hr

        .rsidebar.span_1_of_3
          %ul.sidebar
            %h3 Account
            %li
              Name:
              = current_user.name
            %li
              Email:
              = current_user.email

          .archive
            %h3 Address
            %ul.sidebar
              %li
                Address one:
                = current_user.addr_one
              %li
                Address two:
                = current_user.addr_two
              %li
                City:
                = current_user.city
              %li
                Country:
                = current_user.country
              %li
                Postcode:
                = current_user.postcode
        .clear

app/views/welcome/about.html.haml
- provide(:bg_title, "about us")

/ start main
.main_bg
  .wrap
    .main
      .about
        .cont-grid-img.img_style
          %img{:alt => "", :src => asset_path("about_pic.jpg")}/
        .cont-grid
          %h4 Lorem Ipsum is simply dummy text of the printing and typesetting industry.
          %p.para Lorem Ipsum is simply dummy text of the printing and typesetting industry., Lorem Ipsum  dummy text ever since dummy text of the printing and usings 1500s,Duis aute irure dolor in reprehenderit in voluptate velit esse when an,Lorem Ipsum has been the industry's standard dummy text ever since dummy text of the printing and usings 1500s,
          %p.para There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.
        .clear
        .about-p
          %p.para Lorem Ipsum is simply dummy text of the printing and typesetting industry., Lorem Ipsum  dummy text ever since dummy text of the printing and usings 1500s,Duis aute irure dolor in reprehenderit in voluptate velit esse when an,Lorem Ipsum has been the industry's standard dummy text ever since dummy text of the printing and usings 1500s,
          %p.para Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since dummy text of the printing and usings 1500s,Duis aute irure dolor in reprehenderit in voluptate velit Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since dummy text of the printing and usings 1500s,Duis aute irure dolor in reprehenderit in voluptate velit
          %p.para There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.

app/views/welcome/contact.html.haml
- provide(:bg_title, "contact us")

.main_bg
  .wrap
    .main
      .contact
        .contact_left
          .contact_info
            %h3 Find Us Here
            .map
              %iframe{:frameborder => "0", :height => "175", :marginheight => "0", :marginwidth => "0", :scrolling => "no", :src => "https://maps.google.co.in/maps?f=q&source=s_q&hl=en&geocode=&q=Lighthouse+Point,+FL,+United+States&aq=4&oq=light&sll=26.275636,-80.087265&sspn=0.04941,0.104628&ie=UTF8&hq=&hnear=Lighthouse+Point,+Broward,+Florida,+United+States&t=m&z=14&ll=26.275636,-80.087265&output=embed", :width => "100%"}
              %br/
              %small
                %a{:href => "https://maps.google.co.in/maps?f=q&source=embed&hl=en&geocode=&q=Lighthouse+Point,+FL,+United+States&aq=4&oq=light&sll=26.275636,-80.087265&sspn=0.04941,0.104628&ie=UTF8&hq=&hnear=Lighthouse+Point,+Broward,+Florida,+United+States&t=m&z=14&ll=26.275636,-80.087265", :style => "color:#242424;text-shadow:0 1px 0 #ffffff; text-align:left;font-size:12px;padding: 5px;"} View Larger Map
          .company_address
            %h3 Company Information :
            %p 500 Lorem Ipsum Dolor Sit,
            %p 22-56-2-9 Sit Amet, Lorem,
            %p USA
            %p Phone:(00) 222 666 444
            %p Fax: (000) 000 00 00 0
            %p
              Email:
              %a{:href => "mailto:info@mycompany.com"} info(at)mycompany.com
            %p
              Follow on:
              = succeed "," do
                %a{:href => "#"} Facebook
              %a{:href => "#"} Twitter
        .contact_right
          .contact-form
            %h3 Contact Us
            %form{:action => "contact-post.html", :method => "post"}
              %div
                %span
                  %label NAME
                %span
                  %input.textbox{:name => "userName", :type => "text"}/
              %div
                %span
                  %label E-MAIL
                %span
                  %input.textbox{:name => "userEmail", :type => "text"}/
              %div
                %span
                  %label MOBILE
                %span
                  %input.textbox{:name => "userPhone", :type => "text"}/
              %div
                %span
                  %label SUBJECT
                %span
                  %textarea{:name => "userMsg"}
              %div
                %span
                  %input{:type => "submit", :value => "submit us"}/
        .clear